name: Track issues
on: issues
jobs:
  iss:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Output Issues
        run: echo "${{toJSON(github)}}"
